version: '3'

services:
  app:
    depends_on:
      - mysql
    image: eclipse-temurin:17
    ports:
      - 8081:8080
    tty: true
    volumes:
      - .:/var/www/html/server
    working_dir: /var/www/html/server
  mysql:
    image: mysql:8.0.26
    platform: linux/x86_64
    environment:
      MYSQL_DATABASE: demo_database
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3307:3306
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: