DROP SCHEMA IF EXISTS demo_database;
CREATE SCHEMA demo_database;
USE demo_database;

/** ショップ */
DROP TABLE IF EXISTS users;
CREATE TABLE users(
  id INT(10) NOT NULL AUTO_INCREMENT,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  address VARCHAR(100) NOT NULL,
  create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(id)
)ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
